name: Android CI

on: [ push ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant gradlew execution permission
        run: chmod +x gradlew

      - name: Move gradlew to shared workspace
        run: mv ./gradlew $GITHUB_WORKSPACE/gradlew

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Build project with Gradle
        run: $GITHUB_WORKSPACE/gradlew build

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Test project with Gradle
        run: $GITHUB_WORKSPACE/gradlew test --stacktrace
      - name: Assemble APK file
        run: $GITHUB_WORKSPACE/gradlew assemble